### ISSUE TITLE
没有testmap.mp3这个文件

### ISSUE THREAD

**Issue by zetionclement** [agenthun/WeixinBot#3]
请问可以上传吗？

**Comment by agenthun** [comment]
不需要这个文件的，这个只是测试

**Comment by zetionclement** [comment]
你好，请问这个错误要怎么解决呢？我的环境是CentOS7.5的




------------------ 原始邮件 ------------------
发件人: "agenthun"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 晚上11:13
收件人: "agenthun/WeixinBot"<WeixinBot@noreply.github.com>;
抄送: "海哭゛石未烂"<727553408@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [agenthun/WeixinBot] 没有testmap.mp3这个文件 (#3)




不需要这个文件的，这个只是测试

**Comment by agenthun** [comment]
你把那段代码删掉

**Comment by zetionclement** [comment]
在进行同步线路测试时遇到错误，请问怎么解决呢？
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "weixin.py", line 1095, in listenMsgMode
    self._run('[*] 进行同步线路测试 ... ', self.testsynccheck)
  File "weixin.py", line 1272, in _run
    if func(*args):
  File "weixin.py", line 429, in testsynccheck
    [retcode, selector] = self.synccheck()
  File "weixin.py", line 446, in synccheck
    data = self._get(url)
  File "weixin.py", line 1315, in _get
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 22] Invalid argument>
